name: CI

on:
  push:
    branches: ["**"]     
  pull_request:
    branches: ["**"]
  workflow_dispatch:       

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: okiesdb
          POSTGRES_USER: okies
          POSTGRES_PASSWORD: okies
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U okies -d okiesdb"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Wait for Postgres
        run: |
          for i in {1..40}; do
            pg_isready -h 127.0.0.1 -p 5432 -U okies -d okiesdb && break
            echo "waiting for postgres…"; sleep 3
          done

      - name: Install migrate CLI
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run DB migrations
        run: |
          ~/go/bin/migrate -path infra/migrations \
            -database "postgres://okies:okies@127.0.0.1:5432/okiesdb?sslmode=disable" up

      - name: Go vet
        run: go vet ./...

      - name: Build all
        run: go build ./...

      - name: Unit tests
        run: go test ./...
