name: Backend CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: okies
          POSTGRES_PASSWORD: okies
          POSTGRES_DB: okiesdb
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U okies"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:7
        ports: ['6379:6379']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install deps
        run: go mod tidy
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -v
